help:
	@echo "blink"
	@echo "blink_ext"

blink:
	tinygo flash -target arduino -port /dev/cu.usbmodem141201 blink.go

blink_ext:
	tinygo flash -target arduino -port /dev/cu.usbmodem141201 blink_ext.go

fire:
	tinygo flash -target arduino -port /dev/cu.usbmodem141201 fire.go

